### ISSUE TITLE
Remove class dependencies for JDK >= 1.7

### ISSUE THREAD

**Issue by skovsboll** [xamarinhq/test-cloud-appium-java-extensions#4]
```
java.lang.NoClassDefFoundError: java/util/Base64

	at com.xamarin.testcloud.appium.ShortIdentifier.calcBase64Hash(ShortIdentifier.java:50)
	at com.xamarin.testcloud.appium.ShortIdentifier.shortId(ShortIdentifier.java:35)
	at com.xamarin.testcloud.appium.ShortIdentifier.<init>(ShortIdentifier.java:20)
	at com.xamarin.testcloud.appium.EventReporter.toId(EventReporter.java:79)
	at com.xamarin.testcloud.appium.EventReporter.reportJunit(EventReporter.java:32)
	at com.xamarin.testcloud.appium.Watcher.starting(Watcher.java:36)
```

We're trying to be bytecode compatible with 1.6. It doesn't do much good if we depend on classes that were introduced after 1.6.

**Comment by skovsboll** [comment]
@krukow suggests 

> We could also just internalize this dependency and use:
 
https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html
