### ISSUE TITLE
driver.context don't work.

### ISSUE THREAD

**Issue by m-andrei** [xamarinhq/test-cloud-appium-java-extensions#6]
Hi i can't switch context, i tried different ways from "autoWebView" to directly set context while test (driver.context(contextNames[1])).
And always recieve exception 'wrong capabilities' or timeout exception.
I tried it on different versions of  org.seleniumhq.selenium and io.appium.
Locally all works as expected.

Command duration or timeout: 600.03 seconds
Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26'
System info: host: 'executionhost28.prod', ip: '10.222.150.38', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_31'
Driver info: com.xamarin.testcloud.appium.TestCloudAndroidDriver
Capabilities [{appPackage=com.microsoft.icmmobile, networkConnectionEnabled=true, warnings={}, language=en, databaseEnabled=false, locale=en_US, deviceName=ce061606f4713f3e03, deviceReadyTimeout=120, platform=LINUX, deviceUDID=ce061606f4713f3e03, appActivity=com.microsoft.icmmobile.MainActivity, desired={appPackage=com.microsoft.icmmobile, appActivity=com.microsoft.icmmobile.MainActivity, newCommandTimeout=3000, platformVersion=6.0.1, language=en, platformName=Android, udid=ce061606f4713f3e03, locale=en_US, deviceName=ce061606f4713f3e03, deviceReadyTimeout=120}, newCommandTimeout=3000, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android, udid=ce061606f4713f3e03}]
Session ID: 41dd59a6-a7bc-4280-bf11-57330a63a774
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:546)

**Comment by john7doe** [comment]
Andrei,

If I understand the issue correct, then you are trying to change context to a Webview?

As noted here: https://github.com/xamarinhq/test-cloud-appium-java-extensions#4-current-limitations, we currently do not support Webview.

Br,
/Simon

**Comment by m-andrei** [comment]
if you about
"Automating browsers (web testing) is not supported.".
It is complitly not obvious, could you please then change that you do not support hybrid apps.
Before i started integrate with you, i asked in chat about supporting hybrid apps, and recieve clear answer that you support it.

**Comment by john7doe** [comment]
Updated readme to make it clear that  hybrid apps are currently not supported.
